version: '3.7'

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=mU5W6Fn8h5o1I63M
      - OPENVPN_PASSWORD=iLeFlLCe0EgivyXBQpU2k219B2TQXkdk
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'

  streamonitor:
    build: ./
    image: streamonitor:latest
    volumes:
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      - ./parameters.py:/app/parameters.py
    ports:
      - '6969:6969'
    network_mode: "container:vpn"
    depends_on:
      - vpn
    environment:
      - VPN_GATEWAY=vpn
