version: '3.5'
services:
jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    network_mode: "bridge"
    user: "1000:1000"
    ports:
        - '8096:8096'
    volumes:
        - './jellyfin:/config'
        - '/data/jellyfin/media:/media/misc'
        - '/etc/localtime:/etc/localtime:ro'
