version: "3.4"
services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: bridged
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=Guido
      - nodePort=8267
      - nodeIP=0.0.0.0
      - serverIP=0.0.0.0
      - serverPort=8266   
    volumes:
      - /docker/tdarr/server:/app/server
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /data/tdarr/media:/media
      - /data/tdarr/transcode_cache:/temp
